FROM nginx:stable-alpine

RUN apk add --no-cache gettext
COPY dist/ /usr/share/nginx/html/
COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY entrypoint.sh /docker-entrypoint.d/40-chartdb-config.sh
RUN chmod +x /docker-entrypoint.d/40-chartdb-config.sh

EXPOSE 80
